### ISSUE TITLE
More files and scripts are missing in the repo

### ISSUE THREAD

**Issue by dawnmy** [z2e2/CAMI#2]
The `kmer.txt`, `file.txt`, `total.txt` and `2_fq2fa.sh` are missing in the repo for pipeline_5.

**Comment by dawnmy** [comment]
as well as `output_formatting.py` for pipeline_6

**Comment by z2e2** [comment]
I have uploaded output_formatting.py and 2_fq2fa.sh. file.txt and total.txt will be created when you run pipeline_5_classify_run_all.sh (this will call pipeline_5_classify.sh). You can run ``cat 15 > kmer.txt" to create the kmer.txt.
