### ISSUE TITLE
file_init.txt is not available

### ISSUE THREAD

**Issue by dawnmy** [z2e2/CAMI#3]
https://github.com/z2e2/CAMI/blob/ac70390c9422fb31aed1efa7375e542a3f80c196/pipeline_5_classify_run_all.sh#L8

**Comment by z2e2** [comment]
The file_init.txt should contain the name of sample file you want to classify. For example, if you want to classify sample s4 in marine challenge. Then you can specify the filename (the tar file of shortreads sample 4 file in marine challenge) in file_init.txt. I don't recall the exact filename, let's say it's "/home/data/marine/s4.gz". Then you can run command "echo /home/data/marine/s4.gz > file_init.txt" to create the file_init.txt file. This file basically specify the filename of sample to classify (and assuming it's *.gz). I have also updated the README file to reflect this.
